app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Book, book_schema, books_schema

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/books', methods = ['POST'])
@token_required
def create_book(current_user_token):

    title = request.json['title']
    author_first_name = request.json['author_first_name']
    author_last_name = request.json['author_last_name']
    genre = request.json['genre']
    isbn = request.json['isbn']
    year_published = request.json['year_published']
    language = request.json['language']
    pages = request.json['pages']
    words = request.json['words']
    description = request.json['description']

    user_token = current_user_token.token

    book = Book(title, author_first_name, author_last_name, genre, isbn, year_published, language, pages, words, description, user_token=user_token)

    db.session.add(book)
    db.session.commit()

    response = book_schema.dump(book)
    return jsonify(response)

@api.route('/books', methods = ['GET'])
@token_required
def get_book(current_user_token):
    a_user = current_user_token.token
    books = Book.query.filter_by(user_token = a_user).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/<id>', methods = ['GET'])
@token_required
def get_single_book(current_user_token, id):
    book = Book.query.get(id)
    response = book_schema.dump(book)
    return jsonify(response)

# Update endpoint
@api.route('/books/<id>', methods = ['POST', 'PUT'])
@token_required
def update_book(current_user_token, id):
    book = Book.query.get(id)

    book.title = request.json['title']
    book.author_first_name = request.json['author_first_name']
    book.author_last_name = request.json['author_last_name']
    book.genre = request.json['genre']
    book.isbn = request.json['isbn']
    book.year_published = request.json['year_published']
    book.language = request.json['language']
    book.pages = request.json['pages']
    book.words = request.json['words']
    book.description = request.json['description']

    book.user_token = current_user_token.token

    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

# Delete endpoint
@api.route('/books/<id>', methods = ['DELETE'])
@token_required
def delete_book(current_user_token, id):
    book = Book.query.get(id)
    db.session.delete(book)
    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    print(f'{request.method} , {form.validate_on_submit()}')

    try:
        if request.method == 'POST' and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = form.password.data
            user = User(email, password=password, first_name=first_name, last_name=last_name)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'User-created')
            logged_user = User.query.filter(User.email == email).first()
            login_user(logged_user)
            return redirect(url_for('site.profile'))
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    print(f'{request.method} , {form.validate_on_submit()}')
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your initiation', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('You have failed to log in', 'auth-failed')
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/main.css">
    <title>Table of Contents</title>
</head>
<body>
    <nav>
        <div class="nav-container">
            <h2 class="nav-title">Table of Contents</h2>
            <div class="navbar-list">
                <ul>
                    <li class="nav-item">
                        <a class="nav-button" href="{{ url_for('site.home') }}">Home</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-button" href="{{ url_for('site.profile') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-button" href="{{ url_for('auth.logout') }}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-button" href="{{ url_for('auth.signin') }}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-button" href="{{ url_for('auth.signup') }}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% block content %} 
{% endblock %}
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="block-container">
        <div>
            {% if signup %}
            <div class="input-box">
                {{ form.first_name.label(class = 'form-label') }}
                {{ form.first_name(class = 'form-field', placeholder = 'first name...') }}
            </div>
            <div class="input-box">
                {{ form.last_name.label(class = 'form-label') }}
                {{ form.last_name(class = 'form-field', placeholder = 'last name...') }}
            </div>    
            {% endif %}
            <div class="input-box">
                {{ form.email.label(class = 'form-label') }}
                {{ form.email(class = 'form-field', placeholder = 'email address...') }}
            </div>
            <div class="input-box">
                {{ form.password.label(class = 'form-label') }}
                {{ form.password(class = 'form-field', placeholder = 'password...') }}
            </div>
            {{ form.submit_button(class = 'btn') }}
        </div>
        <div>
            {% if signup %}
            <img src="../static/images/SignUp.jpg" alt="Typewriter">
            {% else %}
            <img src="../static/images/SignIn.jpg" alt="Walking up stairs">
            {% endif %}
        </div>
    </div>
</form>